// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService is the frontend's view of signing in.
 * 
 * There is no Register: accounts are created elsewhere, deliberately.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Account returns who is signed in, or null.
 */
export function Account(): $CancellablePromise<$models.AccountView | null> {
    return $Call.ByID(292775030);
}

/**
 * Login signs in with a username and password.
 */
export function Login(username: string, password: string): $CancellablePromise<$models.LoginResult> {
    return $Call.ByID(638830688, username, password);
}

/**
 * Logout revokes the session.
 */
export function Logout(): $CancellablePromise<$models.LoginResult> {
    return $Call.ByID(3829881765);
}

/**
 * Restore signs in from the stored session, if there is one.
 * 
 * Called once at startup. A result with no account and no error means "nobody
 * was signed in", which is the normal first-run case rather than a failure.
 */
export function Restore(): $CancellablePromise<$models.LoginResult> {
    return $Call.ByID(2252357251);
}

/**
 * SaveSettings persists the configuration and rebuilds the client.
 * 
 * Changing the auth server invalidates the session: tokens are issued by one
 * server and meaningless to another. So this signs the player out rather than
 * leaving them apparently signed in to somewhere they are not.
 */
export function SaveSettings(authURL: string, logFilter: string): $CancellablePromise<$models.LoginResult> {
    return $Call.ByID(851626075, authURL, logFilter);
}

/**
 * Settings returns the current configuration.
 */
export function Settings(): $CancellablePromise<$models.SettingsView> {
    return $Call.ByID(1357343262);
}

/**
 * StoredUsername prefills the form after a session expires.
 */
export function StoredUsername(): $CancellablePromise<string> {
    return $Call.ByID(268798944);
}
