// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameService starts and stops the game.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Launch starts the game.
 * 
 * Returns an empty string on success. The ordering inside is load-bearing and
 * documented step by step below.
 */
export function Launch(): $CancellablePromise<string> {
    return $Call.ByID(3784811516);
}

/**
 * LogPath is where the last run's output was written, for a "reveal" button.
 */
export function LogPath(): $CancellablePromise<string> {
    return $Call.ByID(320334132);
}

/**
 * Status reports what the game process is doing.
 */
export function Status(): $CancellablePromise<$models.GameStatus> {
    return $Call.ByID(3740800325);
}

/**
 * Stop ends the game.
 */
export function Stop(): $CancellablePromise<string> {
    return $Call.ByID(731065659);
}
