// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gamesvc$0 from "../gamesvc/models.js";

/**
 * AccountView is what the UI knows about the signed-in player.
 */
export interface AccountView {
    "id": string;
    "username": string;
}

/**
 * GameStatus mirrors the runner's view of the process.
 */
export type GameStatus = gamesvc$0.Status;

/**
 * LauncherStatus is what the UI needs to decide whether to offer an update to
 * the launcher itself.
 */
export interface LauncherStatus {
    /**
     * Current is the tag this launcher was built from, or "dev".
     */
    "current": string;

    /**
     * Latest is nil when the check could not be made.
     */
    "latest": ReleaseView | null;

    /**
     * UpdateAvailable is true when GitHub publishes a different tag.
     */
    "updateAvailable": boolean;

    /**
     * Staged is true when the update is downloaded and only needs a restart.
     */
    "staged": boolean;

    /**
     * Supported is false when the release has no build for this platform.
     */
    "supported": boolean;

    /**
     * Writable is false when the launcher is installed somewhere it cannot
     * replace itself. Worth knowing before a download rather than after one.
     */
    "writable": boolean;

    /**
     * Dev is true for an unstamped build, which never updates itself.
     */
    "dev": boolean;

    /**
     * Message explains anything the fields above cannot.
     */
    "message": string;
}

/**
 * LoginResult is what the sign-in form gets back.
 */
export interface LoginResult {
    "account": AccountView | null;

    /**
     * Error is empty on success. A message, not a code — the UI shows it.
     */
    "error": string;
}

/**
 * ReleaseView is a release, ready to display.
 */
export interface ReleaseView {
    "tag": string;
    "name": string;
    "publishedAt": string;
    "prerelease": boolean;

    /**
     * NotesHTML is rendered server-side; the notes are not the launcher's own
     * text, so they never reach the page as Markdown to be parsed there.
     */
    "notesHtml": string;
}

/**
 * ServerInfo reports what the account server supports.
 */
export interface ServerInfo {
    "reachable": boolean;
    "version": string;

    /**
     * UpdatesEnabled is false when the server brokers no downloads, so the UI
     * can say so rather than offering a button that answers 501.
     */
    "updatesEnabled": boolean;
    "message": string;
}

/**
 * SettingsView is the launcher's own configuration, for the settings screen.
 */
export interface SettingsView {
    "authUrl": string;

    /**
     * DefaultAuthURL lets the UI show what "empty" means.
     */
    "defaultAuthUrl": string;
    "logFilter": string;

    /**
     * DataDir and VersionsDir are shown read-only, so a player can find their
     * saves without being told where to look.
     */
    "dataDir": string;
    "versionsDir": string;
}

/**
 * UpdateStatus is everything the Play button needs to decide what it says.
 */
export interface UpdateStatus {
    /**
     * InstalledTag is "" when nothing is installed yet.
     */
    "installedTag": string;

    /**
     * Latest is nil when the check could not be made.
     */
    "latest": ReleaseView | null;

    /**
     * UpdateAvailable is true when a different version is published.
     */
    "updateAvailable": boolean;

    /**
     * Playable is true when there is something installed to run.
     */
    "playable": boolean;

    /**
     * Supported is false when the release has no build for this platform.
     */
    "supported": boolean;

    /**
     * Message explains anything the fields above cannot.
     */
    "message": string;
}
