// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService is the player's list of profiles: what exists, which is
 * selected, and what versions there are to pin one to.
 * 
 * A service of its own rather than more methods on UpdateService, because
 * main.go's service list is the frontend's API surface and "profiles" is a
 * coherent noun there.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as install$0 from "../install/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Builds reports the game builds currently unpacked on disk.
 */
export function Builds(): $CancellablePromise<install$0.Build[] | null> {
    return $Call.ByID(686680121);
}

/**
 * Create adds a profile pinned to tag.
 */
export function Create(name: string, tag: string): $CancellablePromise<$models.ProfileList> {
    return $Call.ByID(3052678932, name, tag);
}

/**
 * Delete removes a profile.
 * 
 * The build it pinned stays on disk. Deleting a profile is cheap to regret and
 * re-downloading a few hundred megabytes is not; the build simply stops being
 * pinned, and the next prune may reclaim it.
 */
export function Delete(id: string): $CancellablePromise<$models.ProfileList> {
    return $Call.ByID(1125675179, id);
}

/**
 * List reports every profile, Latest first.
 */
export function List(): $CancellablePromise<$models.ProfileList> {
    return $Call.ByID(3303886776);
}

/**
 * Releases lists the versions a profile can be pinned to.
 * 
 * Needs a bearer token, so it reports the same signed-out and game-running
 * conditions the update check does rather than failing opaquely.
 */
export function Releases(): $CancellablePromise<$models.ReleaseList> {
    return $Call.ByID(2292850906);
}

/**
 * Rename changes a profile's name.
 */
export function Rename(id: string, name: string): $CancellablePromise<$models.ProfileList> {
    return $Call.ByID(4073123282, id, name);
}

/**
 * Retag repins a profile to a different version.
 */
export function Retag(id: string, tag: string): $CancellablePromise<$models.ProfileList> {
    return $Call.ByID(3587182559, id, tag);
}

/**
 * Select changes which profile Play will launch.
 * 
 * Allowed while the game runs: it changes only the *next* launch, and is no
 * more consequential than opening Settings.
 */
export function Select(id: string): $CancellablePromise<$models.ProfileList> {
    return $Call.ByID(3583856920, id);
}
