// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService checks for and installs game builds.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops an install in progress. A no-op when none is running.
 * 
 * The partially downloaded file is kept, so resuming later picks up where this
 * left off rather than starting again.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(1848413830);
}

/**
 * Check reports what is installed and what is available.
 * 
 * Never fails outright: a check that cannot reach the server still reports what
 * is installed, because an offline player with a build should still be able to
 * press Play.
 */
export function Check(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(1881011116);
}

/**
 * Install downloads and unpacks the latest release.
 * 
 * Progress arrives on the "update:progress" event rather than as a return
 * value, so the UI can show a bar while this runs.
 */
export function Install(): $CancellablePromise<string> {
    return $Call.ByID(2636151423);
}

/**
 * Server probes the account server. Unauthenticated, so it works before login.
 */
export function Server(): $CancellablePromise<$models.ServerInfo> {
    return $Call.ByID(4178395527);
}
