// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService checks for and installs game builds.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyLauncherUpdate replaces this launcher with the staged one and restarts.
 * 
 * On success the launcher quits: the process being replaced cannot do the
 * replacing, so the staged build does it and starts the result.
 */
export function ApplyLauncherUpdate(): $CancellablePromise<string> {
    return $Call.ByID(3678226057);
}

/**
 * Cancel stops an install in progress. A no-op when none is running.
 * 
 * The partially downloaded file is kept, so resuming later picks up where this
 * left off rather than starting again.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(1848413830);
}

/**
 * CancelLauncher stops a launcher download in progress. A no-op when none is.
 * 
 * The partially downloaded file is kept, so resuming later picks up where this
 * left off rather than starting again.
 */
export function CancelLauncher(): $CancellablePromise<void> {
    return $Call.ByID(1750221450);
}

/**
 * Check reports what the selected profile needs and whether it can play.
 * 
 * Never fails outright: a check that cannot reach the server still reports what
 * is installed, because an offline player with a build should still be able to
 * press Play. That is also why the forced update is gated on a *successful*
 * check — see UpdateStatus.Required.
 */
export function Check(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(1881011116);
}

/**
 * CheckLauncher reports whether a newer launcher is published.
 * 
 * Never fails outright, for the same reason Check does not: a launcher that
 * cannot reach GitHub is still a working launcher, and saying so is more use
 * than an error.
 */
export function CheckLauncher(): $CancellablePromise<$models.LauncherStatus> {
    return $Call.ByID(2378162748);
}

/**
 * Install downloads and unpacks the latest release.
 * 
 * Progress arrives on the "update:progress" event rather than as a return
 * value, so the UI can show a bar while this runs.
 */
export function Install(): $CancellablePromise<string> {
    return $Call.ByID(2636151423);
}

/**
 * InstallLauncher downloads, verifies and unpacks the newest launcher.
 * 
 * Nothing is replaced here: the build is staged, and ApplyLauncherUpdate puts
 * it in place. Splitting the two keeps the restart something the player asks
 * for rather than something a download does to them.
 * 
 * Progress arrives on the "launcher:progress" event.
 */
export function InstallLauncher(): $CancellablePromise<string> {
    return $Call.ByID(4124118839);
}

/**
 * Server probes the account server. Unauthenticated, so it works before login.
 */
export function Server(): $CancellablePromise<$models.ServerInfo> {
    return $Call.ByID(4178395527);
}
