// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as gamesvc$0 from "../../../../gustaavik/wc-launcher/internal/gamesvc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as install$0 from "../../../../gustaavik/wc-launcher/internal/install/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../gustaavik/wc-launcher/internal/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "auth:changed": services$0.AccountView | null;
            "game:log": string;
            "game:state": gamesvc$0.Status;
            "launcher:progress": install$0.Progress;
            "update:progress": install$0.Progress;
        }
    }
}
