// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is what the UI knows about the game process.
 */
export interface Status {
    "running": boolean;
    "pid": number;

    /**
     * ExitCode is meaningful only once a run has finished. Note that the game
     * exits 0 for almost everything: a bad join address, a failed host bind and
     * a failed world load are all logged and downgraded, leaving the process on
     * the menu. Staying up is the real success signal.
     */
    "exitCode": number;
    "message": string;
}
