// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Build is one unpacked game build on disk.
 */
export interface Build {
    /**
     * Tag is the release this build came from.
     */
    "tag": string;

    /**
     * InstalledAt is when it was moved into place.
     */
    "installedAt": string;
}

/**
 * Progress reports how a download is going.
 */
export interface Progress {
    /**
     * Phase is one of "downloading", "verifying", "extracting", "done".
     */
    "phase": string;

    /**
     * Received and Total are bytes. Total is 0 when the size is unknown.
     */
    "received": number;
    "total": number;

    /**
     * Percent is 0-100, or -1 when Total is unknown.
     */
    "percent": number;
}
